version: '3.8'
services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda-broker
    ports:
      - "9092:9092"       # Kafka API (для Spring Boot)
      - "9644:9644"       # Admin API (для Console)
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level info

      # Kafka Listeners
      - --kafka-addr
      - internal://0.0.0.0:9091
      - --kafka-addr
      - external://0.0.0.0:9092

      # Advertise Listeners
      - --advertise-kafka-addr
      - internal://redpanda:9091
      - --advertise-kafka-addr
      - external://localhost:9092

  console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "9094:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9091
      - ADMIN_API_URL=http://redpanda:9644